In [5]:
## packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import simplejson as json

In [12]:
pd.set_option("display.max_column", 9999)
pd.set_option("display.max_row", 9999)

In [2]:
# path = '/Users/noraxu/MSiA-Google/MSiABlog/yelp_dataset/review.json'
# review = []
# with open(path) as fin:
#     i = 0 
#     for line in fin:
#         line_contents = json.loads(line)
#         review.append(line_contents)

In [6]:
data_review = pd.read_csv('/Users/vikaschaturvedi/Documents/T-Systems/POC/Recommender/Yelp-Recommender-master/data/interim/reviews_atlanta.csv')
print(data_review.shape)
data_review.head()

(637981, 10)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,year
0,Gi5LSRmTXoL9Bp4jNGPjLw,hn0ZbitvmlHnF--KJGJ6_A,TA1KUSCu8GkWP9w0rmElxw,4.0,0,0,0,I have been here twice and have had really goo...,2011-10-27 14:32:57,2011
1,Exip0vNybppf4e3nP9dwnA,lW4awVx0c1Er3ILxfHsYgQ,TA1KUSCu8GkWP9w0rmElxw,4.0,0,0,0,Eating healthy I had the turkey burger it was ...,2014-04-19 16:56:43,2014
2,WhDh4drkByXlQOrjVRH32g,Bt6gmjnWHPERhiOTQOhuEA,TA1KUSCu8GkWP9w0rmElxw,4.0,8,6,9,The only problem with Flip Burger Boutique is ...,2015-11-18 19:21:19,2015
3,vkI2hgdIaPWC84Ni-nxBGw,JxOPt7V1Oz_rdeoUoxm5rA,TA1KUSCu8GkWP9w0rmElxw,4.0,0,1,0,Me and The Piegon went this past Saturday arou...,2009-03-01 09:32:31,2009
4,He3WdC0igkkgDtkyXsdkaw,_2X3YAo_fDkzWOOpVVB1UA,TA1KUSCu8GkWP9w0rmElxw,3.0,1,2,1,ARE YOU SERIOUS? they got that beef tartare?!?...,2013-08-03 20:45:51,2013

In [7]:
print('Total Unique Users in Atlanta:', data_review.user_id.nunique())
print('Total Unique Businesses in Atlanta:', data_review.business_id.nunique())
print('Total Unique Reviews given by those users for the Businesses in Atlanta:', data_review.review_id.nunique())

Total Unique Users in Atlanta: 217169
Total Unique Businesses in Atlanta: 5078
Total Unique Reviews given by those users for the Businesses in Atlanta: 637981

In [8]:
data_review.groupby('user_id').count()['business_id'].describe()

count    217169.000000
mean          2.937717
std           9.234465
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max        1138.000000
Name: business_id, dtype: float64

In [18]:
data_review = pd.read_csv('/Users/vikaschaturvedi/Documents/T-Systems/POC/Recommender/Yelp-Recommender-master/data/interim/reviews_cleaned.csv')
print(data_review.shape)
data_review.head()

(637981, 13)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,year,average_stars,stars_x,stars_x1
0,Gi5LSRmTXoL9Bp4jNGPjLw,hn0ZbitvmlHnF--KJGJ6_A,TA1KUSCu8GkWP9w0rmElxw,4.0,0,0,0,I have been here twice and have had really goo...,2011-10-27 14:32:57,2011,3.26,0.74,1
1,Exip0vNybppf4e3nP9dwnA,lW4awVx0c1Er3ILxfHsYgQ,TA1KUSCu8GkWP9w0rmElxw,4.0,0,0,0,Eating healthy I had the turkey burger it was ...,2014-04-19 16:56:43,2014,3.87,0.13,1
2,WhDh4drkByXlQOrjVRH32g,Bt6gmjnWHPERhiOTQOhuEA,TA1KUSCu8GkWP9w0rmElxw,4.0,8,6,9,The only problem with Flip Burger Boutique is ...,2015-11-18 19:21:19,2015,3.98,0.02,1
3,vkI2hgdIaPWC84Ni-nxBGw,JxOPt7V1Oz_rdeoUoxm5rA,TA1KUSCu8GkWP9w0rmElxw,4.0,0,1,0,Me and The Piegon went this past Saturday arou...,2009-03-01 09:32:31,2009,4.09,-0.09,-1
4,He3WdC0igkkgDtkyXsdkaw,_2X3YAo_fDkzWOOpVVB1UA,TA1KUSCu8GkWP9w0rmElxw,3.0,1,2,1,ARE YOU SERIOUS? they got that beef tartare?!?...,2013-08-03 20:45:51,2013,2.76,0.24,1

In [19]:
data_review.drop(['stars','average_stars','stars_x'],axis=1,inplace=True)

In [14]:
data_business = pd.read_csv('/Users/vikaschaturvedi/Documents/T-Systems/POC/Recommender/Yelp-Recommender-master/data/interim/atlanta_business_Nora2.csv')
print(data_business.shape)
data_business.head()

(5078, 84)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,category,WiFi,RestaurantsGoodForGroups,HasTV,RestaurantsAttire,NoiseLevel,OutdoorSeating,RestaurantsDelivery,RestaurantsReservations,Caters,Alcohol,GoodForKids,BikeParking,RestaurantsPriceRange2,RestaurantsTakeOut,BusinessAcceptsCreditCards,Nightlife,Bars,American (New),Sandwiches,American (Traditional),Coffee & Tea,Fast Food,Breakfast & Brunch,Burgers,Event Planning & Services,Mexican,Pizza,Desserts,Specialty Food,Seafood,Chicken Wings,Salad,Italian,Bakeries,Southern,Cafes,Shopping,Caterers,Beer,Wine & Spirits,Chinese,Cocktail Bars,Asian Fusion,Ice Cream & Frozen Yogurt,Grocery,Sushi Bars,Japanese,Barbeque,Juice Bars & Smoothies,Sports Bars,Lounges,Delis,Mediterranean,Vegetarian,Steakhouses,Arts & Entertainment,Convenience Stores,Tex-Mex,Pubs,Wine Bars,Diners,Venues & Event Spaces,Vegan,Caribbean,Thai,Soul Food,Tapas Bars,Food Trucks,Drugstores,Tapas/Small Plates,Soup,Food Delivery Services,Automotive
0,z8-_6l5EhX5NuPfWzJYQMA,Great Wraps,3393 Peachtree Rd NE,Atlanta,GA,30326.0,33.846335,-84.363578,3.0,11,"Food, Restaurants, Cheesesteaks, Sandwiches, J...",NaN,False,NaN,'casual',NaN,NaN,True,False,NaN,NaN,True,NaN,NaN,True,True,0.0,0.0,0.0,0.444784,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.715482,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Q2vefh0tGhtCGQDK1FI7cw,Piece of Cake,3215 Roswell Rd NE,Atlanta,GA,30305.0,33.842875,-84.378539,4.0,231,"Restaurants, Patisserie/Cake Shop, Desserts, F...",NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True,NaN,NaN,True,2.0,True,True,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.48748,0.0,0.0,0.0,0.000000,0.0,0.513089,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TbZDLpBOl-EbO2LfMySrEg,First China Restaurant,5295 Buford Hwy NE,Atlanta,GA,30340.0,33.896640,-84.280918,3.0,11,"Restaurants, Chinese",NaN,True,NaN,'casual',NaN,False,False,NaN,NaN,u'beer_and_wine',True,NaN,2.0,True,True,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.666292,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,bP6goJODwRnM3AVy45Kn9w,Papi's Cuban & Caribbean Grill,216 Ponce De Leon Ave NE,Atlanta,GA,30308.0,33.772758,-84.380375,4.0,1001,"Caribbean, Cuban, Restaurants",u'free',True,True,'casual',u'average',None,True,False,False,'full_bar',True,True,2.0,True,True,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.361251,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,yCeENvVAGQQ0PeeWU0Pl2g,Nature's Table Bistro,"6000 N Terminal Pkwy, Concourse E Centrepoint,...",Atlanta,GA,30320.0,33.640879,-84.425514,3.5,150,"Restaurants, Sandwiches, Fast Food, American (...",u'free',True,False,u'casual',u'average',False,False,False,False,u'none',True,False,2.0,True,True,0.0,0.0,0.0,0.444784,0.447117,0.0,0.499235,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.604385,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
data_users = pd.read_csv('/Users/vikaschaturvedi/Documents/T-Systems/POC/Recommender/Yelp-Recommender-master/data/interim/users_atlanta.csv')
print(data_users.shape)
data_users.head()

(217169, 24)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,average_stars,compliment_hot,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,is_elite,year
0,q_QQ5kBBwlCcbL1s4NVK3g,Jane,1220,2005-03-14 20:26:35,15038,10030,11291,"2006,2007,2008,2009,2010,2011,2012,2013,2014","xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg...",1357,3.85,1710,163,190,361,147,1212,5691,2541,2541,815,323,True,2005
1,dIIKEfOgo0KqUfGQvGikPg,Gabi,2136,2007-08-10 19:01:51,21272,10289,18046,"2007,2008,2009,2010,2011,2012,2013,2014,2015,2...","XPzYf9_mwG2eXYP2BAGSTA, 2LooM5dcIk2o01nftYdPIg...",1025,4.09,1632,87,94,232,96,1187,3293,2205,2205,472,294,True,2007
2,eCJoZqpV1fDKJGAsXmWXqQ,Bridget,51,2009-07-22 16:47:01,53,14,16,NaN,"DlT1HhrcYfDhjJNUyskU5g, C0ly5C7RzTlzh0M55YspDw...",1,3.86,0,0,0,0,0,3,1,2,2,1,0,False,2009
3,1jXmzuIFKxTnEnR0pxO0Hg,Clara,299,2010-10-01 17:29:36,381,106,121,"2010,2011,2012,2013,2014,2015","VGfzq5na6LZUwxwWO5eVLA, 35uHDsVOEsWbLdEg8Ttobg...",23,3.43,17,8,2,6,0,17,47,30,30,4,1,True,2010
4,MUzkXfPS9JaMgJ907orz0g,Damon,750,2009-01-29 03:48:53,2235,801,893,"2010,2012,2013,2014,2015,2016,2017,2018,2019,2...","dyfc7mHf52_EKUBPHJ1NJw, 4gAD7fnWZNYP3TIMJGyt5A...",86,4.16,40,21,5,3,4,72,165,162,162,54,17,True,2009

In [20]:
user_tag = data_review.merge(data_business, left_on='business_id', right_on='business_id')
print(user_tag.shape)
user_tag.head()

(637981, 93)

,review_id,user_id,business_id,useful,funny,cool,text,date,year,stars_x1,name,address,city,state,postal_code,latitude,longitude,stars,review_count,category,WiFi,RestaurantsGoodForGroups,HasTV,RestaurantsAttire,NoiseLevel,OutdoorSeating,RestaurantsDelivery,RestaurantsReservations,Caters,Alcohol,GoodForKids,BikeParking,RestaurantsPriceRange2,RestaurantsTakeOut,BusinessAcceptsCreditCards,Nightlife,Bars,American (New),Sandwiches,American (Traditional),Coffee & Tea,Fast Food,Breakfast & Brunch,Burgers,Event Planning & Services,Mexican,Pizza,Desserts,Specialty Food,Seafood,Chicken Wings,Salad,Italian,Bakeries,Southern,Cafes,Shopping,Caterers,Beer,Wine & Spirits,Chinese,Cocktail Bars,Asian Fusion,Ice Cream & Frozen Yogurt,Grocery,Sushi Bars,Japanese,Barbeque,Juice Bars & Smoothies,Sports Bars,Lounges,Delis,Mediterranean,Vegetarian,Steakhouses,Arts & Entertainment,Convenience Stores,Tex-Mex,Pubs,Wine Bars,Diners,Venues & Event Spaces,Vegan,Caribbean,Thai,Soul Food,Tapas Bars,Food Trucks,Drugstores,Tapas/Small Plates,Soup,Food Delivery Services,Automotive
0,Gi5LSRmTXoL9Bp4jNGPjLw,hn0ZbitvmlHnF--KJGJ6_A,TA1KUSCu8GkWP9w0rmElxw,0,0,0,I have been here twice and have had really goo...,2011-10-27 14:32:57,2011,1,FLIP burger boutique,1587 Howell Mill Rd,Atlanta,GA,30318.0,33.798343,-84.415749,4.0,1909,"Burgers, Specialty Food, Restaurants, Barbeque...",u'no',True,True,u'casual',u'average',None,True,True,True,u'full_bar',True,True,2.0,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Exip0vNybppf4e3nP9dwnA,lW4awVx0c1Er3ILxfHsYgQ,TA1KUSCu8GkWP9w0rmElxw,0,0,0,Eating healthy I had the turkey burger it was ...,2014-04-19 16:56:43,2014,1,FLIP burger boutique,1587 Howell Mill Rd,Atlanta,GA,30318.0,33.798343,-84.415749,4.0,1909,"Burgers, Specialty Food, Restaurants, Barbeque...",u'no',True,True,u'casual',u'average',None,True,True,True,u'full_bar',True,True,2.0,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,WhDh4drkByXlQOrjVRH32g,Bt6gmjnWHPERhiOTQOhuEA,TA1KUSCu8GkWP9w0rmElxw,8,6,9,The only problem with Flip Burger Boutique is ...,2015-11-18 19:21:19,2015,1,FLIP burger boutique,1587 Howell Mill Rd,Atlanta,GA,30318.0,33.798343,-84.415749,4.0,1909,"Burgers, Specialty Food, Restaurants, Barbeque...",u'no',True,True,u'casual',u'average',None,True,True,True,u'full_bar',True,True,2.0,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,vkI2hgdIaPWC84Ni-nxBGw,JxOPt7V1Oz_rdeoUoxm5rA,TA1KUSCu8GkWP9w0rmElxw,0,1,0,Me and The Piegon went this past Saturday arou...,2009-03-01 09:32:31,2009,-1,FLIP burger boutique,1587 Howell Mill Rd,Atlanta,GA,30318.0,33.798343,-84.415749,4.0,1909,"Burgers, Specialty Food, Restaurants, Barbeque...",u'no',True,True,u'casual',u'average',None,True,True,True,u'full_bar',True,True,2.0,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,He3WdC0igkkgDtkyXsdkaw,_2X3YAo_fDkzWOOpVVB1UA,TA1KUSCu8GkWP9w0rmElxw,1,2,1,ARE YOU SERIOUS? they got that beef tartare?!?...,2013-08-03 20:45:51,2013,1,FLIP burger boutique,1587 Howell Mill Rd,Atlanta,GA,30318.0,33.798343,-84.415749,4.0,1909,"Burgers, Specialty Food, Restaurants, Barbeque...",u'no',True,True,u'casual',u'average',None,True,True,True,u'full_bar',True,True,2.0,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,business_id,cool,date,funny,review_id,stars_x,text,useful,user_id,year,...,Halal,Gluten-Free,Food Delivery Services,Wine Bars,Delis,Health Markets,Tea Rooms,Sports Bars,Gastropubs,Tapas/Small Plates
0,AakkkTuGZA2KBodKi2_u8A,0.0,2012-07-16 00:37:14,0.693147,JVcjMhlavKKn3UIt9p9OXA,-1.0,I cannot believe how things have changed in 3 ...,0.693147,TpyOT5E16YASd7EWjLQlrw,2012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AakkkTuGZA2KBodKi2_u8A,0.0,2014-02-24 01:45:02,0.000000,vKhtzhPUz9RJbllyvHm3qA,-1.0,"Pretty good, food,, about the same as other vi...",0.000000,G-9ujgKmc1J2k7HSqXszsw,2014,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AakkkTuGZA2KBodKi2_u8A,0.0,2016-02-12 00:25:23,0.000000,Je6AF9sTKwXwOVw2YHR1dg,1.0,I've been going to this place since it opened ...,0.000000,NA4sslQXta6U263fqzwKiw,2016,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AakkkTuGZA2KBodKi2_u8A,0.0,2013-05-07 06:03:17,0.000000,b_xVF8U5Vqljz58OUEjqgA,1.0,One of the best Vietnamese places I`ve tried i...,0.693147,1fNQRju9gmoCEvbPQBSo7w,2013,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AakkkTuGZA2KBodKi2_u8A,0.0,2011-11-30 16:46:24,0.000000,vFPpG1xDBSWcvy_165fxKg,-1.0,"This place is just ok. Nice atmosphere, big op...",0.000000,fYJGKhZK2FZckYWDMdCooA,2011,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
user_tag.columns

Index(['review_id', 'user_id', 'business_id', 'useful', 'funny', 'cool',
       'text', 'date', 'year', 'stars_x1', 'name', 'address', 'city', 'state',
       'postal_code', 'latitude', 'longitude', 'stars', 'review_count',
       'category', 'WiFi', 'RestaurantsGoodForGroups', 'HasTV',
       'RestaurantsAttire', 'NoiseLevel', 'OutdoorSeating',
       'RestaurantsDelivery', 'RestaurantsReservations', 'Caters', 'Alcohol',
       'GoodForKids', 'BikeParking', 'RestaurantsPriceRange2',
       'RestaurantsTakeOut', 'BusinessAcceptsCreditCards', 'Nightlife', 'Bars',
       'American (New)', 'Sandwiches', 'American (Traditional)',
       'Coffee & Tea', 'Fast Food', 'Breakfast & Brunch', 'Burgers',
       'Event Planning & Services', 'Mexican', 'Pizza', 'Desserts',
       'Specialty Food', 'Seafood', 'Chicken Wings', 'Salad', 'Italian',
       'Bakeries', 'Southern', 'Cafes', 'Shopping', 'Caterers', 'Beer',
       'Wine & Spirits', 'Chinese', 'Cocktail Bars', 'Asian Fusion',
       'Ice Cream & Frozen Yogurt', 'Grocery', 'Sushi Bars', 'Japanese',
       'Barbeque', 'Juice Bars & Smoothies', 'Sports Bars', 'Lounges', 'Delis',
       'Mediterranean', 'Vegetarian', 'Steakhouses', 'Arts & Entertainment',
       'Convenience Stores', 'Tex-Mex', 'Pubs', 'Wine Bars', 'Diners',
       'Venues & Event Spaces', 'Vegan', 'Caribbean', 'Thai', 'Soul Food',
       'Tapas Bars', 'Food Trucks', 'Drugstores', 'Tapas/Small Plates', 'Soup',
       'Food Delivery Services', 'Automotive'],
      dtype='object')

In [22]:
user_tag.iloc[:,33:].head()

,RestaurantsTakeOut,BusinessAcceptsCreditCards,Nightlife,Bars,American (New),Sandwiches,American (Traditional),Coffee & Tea,Fast Food,Breakfast & Brunch,Burgers,Event Planning & Services,Mexican,Pizza,Desserts,Specialty Food,Seafood,Chicken Wings,Salad,Italian,Bakeries,Southern,Cafes,Shopping,Caterers,Beer,Wine & Spirits,Chinese,Cocktail Bars,Asian Fusion,Ice Cream & Frozen Yogurt,Grocery,Sushi Bars,Japanese,Barbeque,Juice Bars & Smoothies,Sports Bars,Lounges,Delis,Mediterranean,Vegetarian,Steakhouses,Arts & Entertainment,Convenience Stores,Tex-Mex,Pubs,Wine Bars,Diners,Venues & Event Spaces,Vegan,Caribbean,Thai,Soul Food,Tapas Bars,Food Trucks,Drugstores,Tapas/Small Plates,Soup,Food Delivery Services,Automotive
0,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,True,True,0.231408,0.236681,0.266708,0.0,0.0,0.0,0.0,0.0,0.333083,0.0,0.0,0.0,0.0,0.366849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
user_tag2 = user_tag.groupby('user_id').sum().iloc[:,30:]
user_tag2.shape

(217169, 38)

In [25]:
user_tag2.head()

,Cafes,Shopping,Caterers,Beer,Wine & Spirits,Chinese,Cocktail Bars,Asian Fusion,Ice Cream & Frozen Yogurt,Grocery,Sushi Bars,Japanese,Barbeque,Juice Bars & Smoothies,Sports Bars,Lounges,Delis,Mediterranean,Vegetarian,Steakhouses,Arts & Entertainment,Convenience Stores,Tex-Mex,Pubs,Wine Bars,Diners,Venues & Event Spaces,Vegan,Caribbean,Thai,Soul Food,Tapas Bars,Food Trucks,Drugstores,Tapas/Small Plates,Soup,Food Delivery Services,Automotive
user_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
--0DrQkM0FT-yCQRWw82uQ,0.0,0.0,0.0,0.539985,0.539985,0.555431,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
--0YW17u1XvJ75JTWzhzjw,0.0,0.0,0.0,0.359990,0.359990,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.705119,0.000000,0.0,0.39749,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
--1orhUoGFSdHXsoxqQc8g,0.0,0.0,0.0,0.231422,0.231422,0.000000,0.000000,0.244178,0.0,0.0,0.000000,0.000000,1.181565,0.0,0.00000,0.0,0.0,0.000000,0.741107,0.0,0.0,0.0,0.0,0.0,0.0,1.240417,0.0,0.0,0.81675,0.292509,0.0,0.0,0.845969,0.0,0.000000,0.0,0.0,0.0
--3hy9856ikQL_klJ3hXmA,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.559765,0.000000,0.0,0.0,0.585513,0.587599,0.000000,0.0,0.00000,0.0,0.0,0.917044,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0
--3r3ei2_Q2X1-y_3IISaQ,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.479799,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.613981,0.0,0.0,0.0

In [26]:
tag = []
for i in range(user_tag2.shape[0]):
    tmp = user_tag2.iloc[i,:].sort_values(ascending=False)[:2].index.tolist()
    tag.extend(tmp)

len(set(tag))

38

In [27]:
tag_all = user_tag2.idxmax(axis=1)
tag_list = list(set(tag_all))
tag_all_df = pd.DataFrame(tag_all).reset_index()

for tag in tag_list:
    data_users[tag] = 0

In [28]:
for ind,val in enumerate(tag_all):
    row = list(data_users['user_id']).index(tag_all_df['user_id'][ind])
    data_users.loc[row,val] = 1

In [29]:
print(data_users.shape)
data_users.head()

(217169, 61)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,average_stars,compliment_hot,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,is_elite,year,Ice Cream & Frozen Yogurt,Cocktail Bars,Chinese,Caterers,Cafes,Caribbean,Thai,Tex-Mex,Shopping,Sushi Bars,Delis,Japanese,Vegetarian,Wine Bars,Juice Bars & Smoothies,Tapas Bars,Arts & Entertainment,Beer,Mediterranean,Automotive,Diners,Pubs,Vegan,Soup,Tapas/Small Plates,Steakhouses,Food Delivery Services,Venues & Event Spaces,Soul Food,Drugstores,Grocery,Convenience Stores,Lounges,Sports Bars,Food Trucks,Barbeque,Asian Fusion
0,q_QQ5kBBwlCcbL1s4NVK3g,Jane,1220,2005-03-14 20:26:35,15038,10030,11291,"2006,2007,2008,2009,2010,2011,2012,2013,2014","xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg...",1357,3.85,1710,163,190,361,147,1212,5691,2541,2541,815,323,True,2005,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,dIIKEfOgo0KqUfGQvGikPg,Gabi,2136,2007-08-10 19:01:51,21272,10289,18046,"2007,2008,2009,2010,2011,2012,2013,2014,2015,2...","XPzYf9_mwG2eXYP2BAGSTA, 2LooM5dcIk2o01nftYdPIg...",1025,4.09,1632,87,94,232,96,1187,3293,2205,2205,472,294,True,2007,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,eCJoZqpV1fDKJGAsXmWXqQ,Bridget,51,2009-07-22 16:47:01,53,14,16,NaN,"DlT1HhrcYfDhjJNUyskU5g, C0ly5C7RzTlzh0M55YspDw...",1,3.86,0,0,0,0,0,3,1,2,2,1,0,False,2009,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,1jXmzuIFKxTnEnR0pxO0Hg,Clara,299,2010-10-01 17:29:36,381,106,121,"2010,2011,2012,2013,2014,2015","VGfzq5na6LZUwxwWO5eVLA, 35uHDsVOEsWbLdEg8Ttobg...",23,3.43,17,8,2,6,0,17,47,30,30,4,1,True,2010,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,MUzkXfPS9JaMgJ907orz0g,Damon,750,2009-01-29 03:48:53,2235,801,893,"2010,2012,2013,2014,2015,2016,2017,2018,2019,2...","dyfc7mHf52_EKUBPHJ1NJw, 4gAD7fnWZNYP3TIMJGyt5A...",86,4.16,40,21,5,3,4,72,165,162,162,54,17,True,2009,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [19]:
data_users.iloc[:,24:].describe()

,Vietnamese,Pubs,Arts & Entertainment,Caterers,American (New),Chicken Wings,Ethnic Food,Barbeque,Greek,Gastropubs,...,Salad,Food Delivery Services,Comfort Food,Mexican,Sports Bars,Caribbean,Beer,Seafood,Shopping,Health Markets
count,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.00000,...,92381.00000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000,92381.000000
mean,0.017969,0.066832,0.005412,0.024983,0.075048,0.013185,0.010846,0.019972,0.011831,0.00381,...,0.01733,0.004568,0.012546,0.066280,0.006960,0.008811,0.016118,0.048397,0.014895,0.000963
std,0.132840,0.249732,0.073370,0.156076,0.263470,0.114065,0.103580,0.139903,0.108128,0.06161,...,0.13050,0.067433,0.111304,0.248772,0.083138,0.093455,0.125930,0.214606,0.121133,0.031024
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [32]:
data_users.describe()

,review_count,useful,funny,cool,fans,average_stars,compliment_hot,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,year,Ice Cream & Frozen Yogurt,Cocktail Bars,Chinese,Caterers,Cafes,Caribbean,Thai,Tex-Mex,Shopping,Sushi Bars,Delis,Japanese,Vegetarian,Wine Bars,Juice Bars & Smoothies,Tapas Bars,Arts & Entertainment,Beer,Mediterranean,Automotive,Diners,Pubs,Vegan,Soup,Tapas/Small Plates,Steakhouses,Food Delivery Services,Venues & Event Spaces,Soul Food,Drugstores,Grocery,Convenience Stores,Lounges,Sports Bars,Food Trucks,Barbeque,Asian Fusion
count,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.00000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.00000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000,217169.000000
mean,39.454181,81.662443,34.279847,48.773338,3.029134,3.663057,3.333293,0.556792,0.333082,0.250335,0.129111,2.820997,6.519296,5.618707,5.618707,2.195428,2.214800,2013.691415,0.021205,0.026417,0.018327,0.012525,0.245956,0.018133,0.036598,0.032132,0.006078,0.017466,0.012796,0.03046,0.017622,0.020938,0.010397,0.020394,0.013708,0.014021,0.025855,0.002417,0.027780,0.03064,0.034416,0.016844,0.027766,0.049505,0.010250,0.036916,0.041438,0.002850,0.006516,0.000663,0.016582,0.025119,0.004945,0.047857,0.016466
std,136.701157,979.729772,648.032750,853.039045,28.152563,1.020630,79.306959,11.030615,15.430432,9.016472,6.057222,49.416028,232.107454,140.425417,140.425417,45.257098,130.824645,2.964962,0.144066,0.160373,0.134130,0.111211,0.430654,0.133434,0.187774,0.176350,0.077726,0.130999,0.112396,0.17185,0.131574,0.143176,0.101437,0.141345,0.116277,0.117579,0.158704,0.049108,0.164343,0.17234,0.182295,0.128687,0.164303,0.216921,0.100723,0.188556,0.199301,0.053312,0.080456,0.025742,0.127698,0.156486,0.070150,0.213464,0.127261
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2004.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,1.000000,0.000000,0.000000,0.000000,3.130000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2011.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,9.000000,5.000000,1.000000,1.000000,0.000000,3.830000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2014.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,26.000000,21.000000,4.000000,5.000000,1.000000,4.380000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2016.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,14691.000000,182600.000000,166330.000000,175463.000000,3237.000000,5.000000,20249.000000,4053.000000,6365.000000,2962.000000,2412.000000,13248.000000,90858.000000,46858.000000,46858.000000,15225.000000,53854.000000,2021.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [31]:
data_users.to_csv('/Users/vikaschaturvedi/Documents/T-Systems/POC/Recommender/Yelp-Recommender-master/data/preprocessed//users_tag.csv',index=False)